### ISSUE TITLE
Installation - confused

### ISSUE THREAD

**Issue by guussie** [bazwilliams/upnp-playlist-service#10]
I am confused with the installation instructions. When I run npm install the process will look for package.son in home/pi but further on you suggest that the software should be installed in /opt/ but when I do that, npm install gives an error message

**Comment by bazwilliams** [comment]
Once you have cloned the repository run `npm install` inside the `upnp-playlist-service` folder. this should download the necessary dependencies into the `upnp-playlist-service/node-modules` folder. You can then start the service from the `upnp-playlist-service` folder. 

You don't have to install in /opt that is just convention. No reason not to install in your own home folder. I plan to create a deb file for easier installation soon. 

Wherever you clone the repository, you'll need to make she your permissions are suitable for creating the `node-modules` folder and a `persist` folder.
