### ISSUE TITLE
Can't install on Raspberry Pi

### ISSUE THREAD

**Issue by guussie** [bazwilliams/upnp-playlist-service#12]
I tried to install on Raspberry Pi but it doesn't seem to work for armhf.

Can this software run on Raspberry Pi and if so, can you post installation instructions?

Thanks,

Guus

**Comment by bazwilliams** [comment]
Thanks for the report. I've just tried manually installing it on mine by cloning the repository. When I do an npm install and run I get the following error with node v0.10.36 (installed from http://redandwhite.herokuapp.com/#/):

```

dgram.js:88
  throw new Error('Bad socket type specified. Valid types are: udp4, udp6');
        ^
Error: Bad socket type specified. Valid types are: udp4, udp6
    at newHandle (dgram.js:88:9)
    at new Socket (dgram.js:113:16)
    at Object.exports.createSocket (dgram.js:130:10)
    at new Ssdp (/home/barry/upnp-playlist-service/node_modules/node-upnp-ssdp/index.js:83:25)
    at Object.<anonymous> (/home/barry/upnp-playlist-service/node_modules/node-upnp-ssdp/index.js:128:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by guussie** [comment]
I reinstalled node with the link you gave. It seems to install.

I then ran:
   npm install upnp-playlist-service-0.0.5.deb

and get the following error messages:

npm ERR! not a package /tmp/npm-6444-NG76hMWC/1443767049570-0.9083089258056134/tmp.tgz
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'upnp-playlist-service-0.0.5.deb' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.1.6+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "upnp-playlist-service-0.0.5.deb"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

I then tried this:

```
 sudo dpkg -i upnp-playlist-service-0.0.5.deb
```

I get the following error message:

dpkg: error processing upnp-playlist-service-0.0.5.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 upnp-playlist-service-0.0.5.deb

I have cloned the playlist service to my Mac's desktop, then to the RPi.

I am using an RPi B+

**Comment by bazwilliams** [comment]
Sorry, I should have been a bit clearer. The deb file won't work as it has the wrong arch type.

NPM is a node package manager which will install other npm modules. (Have a read of http://howtonode.org/introduction-to-npm). 

Once you have the cloned repo on your raspberry pi, just run `npm install` in the upnp-playlist-service folder. This will go away and download the necessary modules, you may have to do this more than once due to conflicting dependencies. 

This will get you in a better point, but I still don't think it works with the raspberry pi for some reason which I'll look into. Once I've fixed that, I'll investigate a .deb file for raspbi too.

**Comment by guussie** [comment]
No problem, I am learning here....

I installed node.js as per your suggestion.

Then I copied the upnp-playlist folder into the Home directory.

Then:

  cd upnp*

Then:

  npm install

First time took some time. Second time was much faster with no error messages.

  npm ls

Result:

pi@Bedroom ~/upnp-playlist-service $ npm ls
upnp-playlist-service@0.0.5 /home/pi/upnp-playlist-service
├── angularjs@0.0.1
├── async@0.9.2
├─┬ binary@0.3.0
│ ├── buffers@0.1.1
│ └─┬ chainsaw@0.1.0
│   └── traverse@0.3.9
├─┬ body-parser@1.9.3
│ ├── bytes@1.0.0
│ ├── depd@1.0.1
│ ├── iconv-lite@0.4.5
│ ├── media-typer@0.3.0
│ ├─┬ on-finished@2.1.1
│ │ └── ee-first@1.1.0
│ ├── qs@2.3.3
│ ├── raw-body@1.3.1
│ └─┬ type-is@1.5.7
│   └─┬ mime-types@2.0.14
│     └── mime-db@1.12.0
├─┬ bower@1.5.3
│ ├── abbrev@1.0.7
│ ├── archy@1.0.0
│ ├─┬ bower-config@0.6.1
│ │ ├── graceful-fs@2.0.3
│ │ ├── mout@0.9.1
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ └── osenv@0.0.3
│ ├── bower-endpoint-parser@0.2.2
│ ├─┬ bower-json@0.4.0
│ │ ├── deep-extend@0.2.11
│ │ ├── graceful-fs@2.0.3
│ │ └── intersect@0.0.3
│ ├── bower-logger@0.2.2
│ ├─┬ bower-registry-client@0.3.0
│ │ ├── async@0.2.10
│ │ ├── graceful-fs@2.0.3
│ │ ├── lru-cache@2.3.1
│ │ ├── mkdirp@0.3.5
│ │ ├─┬ request@2.51.0
│ │ │ ├── aws-sign2@0.5.0
│ │ │ ├─┬ bl@0.9.4
│ │ │ │ └─┬ readable-stream@1.0.33
│ │ │ │   ├── core-util-is@1.0.1
│ │ │ │   ├── inherits@2.0.1
│ │ │ │   ├── isarray@0.0.1
│ │ │ │   └── string_decoder@0.10.31
│ │ │ ├── caseless@0.8.0
│ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ └── delayed-stream@0.0.5
│ │ │ ├── forever-agent@0.5.2
│ │ │ ├─┬ form-data@0.2.0
│ │ │ │ ├── async@0.9.2
│ │ │ │ └─┬ mime-types@2.0.14
│ │ │ │   └── mime-db@1.12.0
│ │ │ ├─┬ hawk@1.1.1
│ │ │ │ ├── boom@0.4.2
│ │ │ │ ├── cryptiles@0.2.2
│ │ │ │ ├── hoek@0.9.1
│ │ │ │ └── sntp@0.2.4
│ │ │ ├─┬ http-signature@0.10.1
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.5
│ │ │ │ └── ctype@0.5.3
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├── mime-types@1.0.2
│ │ │ ├── oauth-sign@0.5.0
│ │ │ ├── qs@2.3.3
│ │ │ ├── stringstream@0.0.4
│ │ │ ├── tough-cookie@2.0.0
│ │ │ └── tunnel-agent@0.4.1
│ │ ├── request-replay@0.2.0
│ │ └── rimraf@2.2.8
│ ├─┬ cardinal@0.4.4
│ │ ├── ansicolors@0.2.1
│ │ └─┬ redeyed@0.4.4
│ │   └── esprima@1.0.4
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├─┬ strip-ansi@3.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ └── supports-color@2.0.0
│ ├── chmodr@0.1.0
│ ├─┬ configstore@0.3.2
│ │ ├─┬ js-yaml@3.4.2
│ │ │ ├─┬ argparse@1.0.2
│ │ │ │ ├── lodash@3.10.1
│ │ │ │ └── sprintf-js@1.0.3
│ │ │ └── esprima@2.2.0
│ │ ├── object-assign@2.1.1
│ │ ├─┬ osenv@0.1.3
│ │ │ ├── os-homedir@1.0.1
│ │ │ └── os-tmpdir@1.0.1
│ │ ├── uuid@2.0.1
│ │ └── xdg-basedir@1.0.1
│ ├─┬ decompress-zip@0.1.0
│ │ ├── mkpath@0.1.0
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └─┬ touch@0.0.3
│ │   └── nopt@1.0.10
│ ├─┬ fstream@1.0.8
│ │ ├── graceful-fs@4.1.2
│ │ └── inherits@2.0.1
│ ├─┬ fstream-ignore@1.0.2
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@2.0.10
│ │   └─┬ brace-expansion@1.1.1
│ │     ├── balanced-match@0.2.0
│ │     └── concat-map@0.0.1
│ ├─┬ github@0.2.4
│ │ └── mime@1.3.4
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.1
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.2
│ │   └── wrappy@1.0.1
│ ├── graceful-fs@3.0.8
│ ├─┬ handlebars@2.0.0
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.0
│ ├─┬ inquirer@0.8.0
│ │ ├── ansi-regex@1.1.1
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├── escape-string-regexp@1.0.3
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├─┬ strip-ansi@0.3.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └── supports-color@0.2.0
│ │ ├─┬ cli-color@0.3.3
│ │ │ ├── d@0.1.1
│ │ │ ├─┬ es5-ext@0.10.7
│ │ │ │ ├── es6-iterator@0.1.3
│ │ │ │ └── es6-symbol@2.0.1
│ │ │ ├─┬ memoizee@0.3.9
│ │ │ │ ├─┬ es6-weak-map@0.1.4
│ │ │ │ │ ├── es6-iterator@0.1.3
│ │ │ │ │ └── es6-symbol@2.0.1
│ │ │ │ ├── event-emitter@0.3.3
│ │ │ │ ├── lru-queue@0.1.0
│ │ │ │ └── next-tick@0.2.2
│ │ │ └─┬ timers-ext@0.1.0
│ │ │   └── next-tick@0.2.2
│ │ ├── figures@1.4.0
│ │ ├── lodash@2.4.2
│ │ ├── mute-stream@0.0.4
│ │ ├─┬ readline2@0.1.1
│ │ │ └── strip-ansi@2.0.1
│ │ ├── rx@2.5.3
│ │ └── through@2.3.8
│ ├─┬ insight@0.7.0
│ │ ├── async@1.4.2
│ │ ├─┬ configstore@1.2.1
│ │ │ ├── graceful-fs@4.1.2
│ │ │ ├── object-assign@3.0.0
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ ├─┬ osenv@0.1.3
│ │ │ │ └── os-homedir@1.0.1
│ │ │ ├── uuid@2.0.1
│ │ │ ├─┬ write-file-atomic@1.1.3
│ │ │ │ └── slide@1.1.6
│ │ │ └─┬ xdg-basedir@2.0.0
│ │ │   └── os-homedir@1.0.1
│ │ ├─┬ inquirer@0.10.1
│ │ │ ├── ansi-escapes@1.1.0
│ │ │ ├── ansi-regex@2.0.0
│ │ │ ├─┬ cli-cursor@1.0.2
│ │ │ │ └─┬ restore-cursor@1.0.1
│ │ │ │   ├── exit-hook@1.1.1
│ │ │ │   └── onetime@1.0.0
│ │ │ ├── cli-width@1.0.1
│ │ │ ├── figures@1.4.0
│ │ │ ├── lodash@3.10.1
│ │ │ ├─┬ readline2@1.0.1
│ │ │ │ ├─┬ code-point-at@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.0
│ │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│ │ │ │ │ └── number-is-nan@1.0.0
│ │ │ │ └── mute-stream@0.0.5
│ │ │ ├─┬ run-async@0.1.0
│ │ │ │ └─┬ once@1.3.2
│ │ │ │   └── wrappy@1.0.1
│ │ │ ├── rx-lite@3.1.2
│ │ │ ├── strip-ansi@3.0.0
│ │ │ └── through@2.3.8
│ │ ├─┬ lodash.debounce@3.1.1
│ │ │ └── lodash._getnative@3.9.1
│ │ ├── object-assign@4.0.1
│ │ ├─┬ os-name@1.0.3
│ │ │ ├─┬ osx-release@1.1.0
│ │ │ │ └── minimist@1.2.0
│ │ │ └─┬ win-release@1.1.1
│ │ │   └── semver@5.0.3
│ │ └── tough-cookie@2.0.0
│ ├── is-root@1.0.0
│ ├── junk@1.0.2
│ ├── lockfile@1.0.1
│ ├── lru-cache@2.7.0
│ ├─┬ md5-hex@1.1.0
│ │ └── md5-o-matic@0.1.1
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├── mout@0.11.0
│ ├── nopt@3.0.4
│ ├── opn@1.0.2
│ ├─┬ p-throttler@0.1.1
│ │ └── q@0.9.7
│ ├─┬ promptly@0.2.0
│ │ └─┬ read@1.0.7
│ │   └── mute-stream@0.0.5
│ ├── q@1.4.1
│ ├─┬ request@2.53.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.9.0
│ │ ├─┬ combined-stream@0.0.7
│ │ │ └── delayed-stream@0.0.5
│ │ ├── forever-agent@0.5.2
│ │ ├── form-data@0.2.0
│ │ ├─┬ hawk@2.3.1
│ │ │ ├── boom@2.9.0
│ │ │ ├── cryptiles@2.0.5
│ │ │ ├── hoek@2.16.3
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@0.10.1
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.0.14
│ │ │ └── mime-db@1.12.0
│ │ ├── oauth-sign@0.6.0
│ │ ├── qs@2.3.3
│ │ ├── stringstream@0.0.4
│ │ ├── tough-cookie@2.0.0
│ │ └── tunnel-agent@0.4.1
│ ├─┬ request-progress@0.3.1
│ │ └── throttleit@0.0.2
│ ├── retry@0.6.1
│ ├─┬ rimraf@2.4.3
│ │ └─┬ glob@5.0.15
│ │   ├─┬ inflight@1.0.4
│ │   │ └── wrappy@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├─┬ minimatch@3.0.0
│ │   │ └─┬ brace-expansion@1.1.1
│ │   │   ├── balanced-match@0.2.0
│ │   │   └── concat-map@0.0.1
│ │   ├─┬ once@1.3.2
│ │   │ └── wrappy@1.0.1
│ │   └── path-is-absolute@1.0.0
│ ├── semver@2.3.2
│ ├─┬ shell-quote@1.4.3
│ │ ├── array-filter@0.0.1
│ │ ├── array-map@0.0.0
│ │ ├── array-reduce@0.0.0
│ │ └── jsonify@0.0.0
│ ├── stringify-object@1.0.1
│ ├─┬ tar-fs@1.8.1
│ │ ├─┬ pump@1.0.0
│ │ │ ├── end-of-stream@1.1.0
│ │ │ └─┬ once@1.3.2
│ │ │   └── wrappy@1.0.1
│ │ └─┬ tar-stream@1.2.1
│ │   ├── bl@1.0.0
│ │   ├─┬ end-of-stream@1.1.0
│ │   │ └─┬ once@1.3.2
│ │   │   └── wrappy@1.0.1
│ │   ├─┬ readable-stream@2.0.2
│ │   │ ├── core-util-is@1.0.1
│ │   │ ├── inherits@2.0.1
│ │   │ ├── isarray@0.0.1
│ │   │ ├── process-nextick-args@1.0.3
│ │   │ ├── string_decoder@0.10.31
│ │   │ └── util-deprecate@1.0.1
│ │   └── xtend@4.0.0
│ ├── tmp@0.0.24
│ ├─┬ update-notifier@0.3.2
│ │ ├── is-npm@1.0.0
│ │ ├─┬ latest-version@1.0.1
│ │ │ └─┬ package-json@1.2.0
│ │ │   ├─┬ got@3.3.1
│ │ │   │ ├─┬ duplexify@3.4.2
│ │ │   │ │ ├─┬ end-of-stream@1.0.0
│ │ │   │ │ │ └─┬ once@1.3.2
│ │ │   │ │ │   └── wrappy@1.0.1
│ │ │   │ │ └─┬ readable-stream@2.0.2
│ │ │   │ │   ├── core-util-is@1.0.1
│ │ │   │ │   ├── inherits@2.0.1
│ │ │   │ │   ├── isarray@0.0.1
│ │ │   │ │   ├── process-nextick-args@1.0.3
│ │ │   │ │   ├── string_decoder@0.10.31
│ │ │   │ │   └── util-deprecate@1.0.1
│ │ │   │ ├── infinity-agent@2.0.3
│ │ │   │ ├── is-redirect@1.0.0
│ │ │   │ ├── is-stream@1.0.1
│ │ │   │ ├── lowercase-keys@1.0.0
│ │ │   │ ├─┬ nested-error-stacks@1.0.1
│ │ │   │ │ └── inherits@2.0.1
│ │ │   │ ├── object-assign@3.0.0
│ │ │   │ ├── prepend-http@1.0.3
│ │ │   │ ├─┬ read-all-stream@3.0.1
│ │ │   │ │ ├─┬ pinkie-promise@1.0.0
│ │ │   │ │ │ └── pinkie@1.0.0
│ │ │   │ │ └─┬ readable-stream@2.0.2
│ │ │   │ │   ├── core-util-is@1.0.1
│ │ │   │ │   ├── inherits@2.0.1
│ │ │   │ │   ├── isarray@0.0.1
│ │ │   │ │   ├── process-nextick-args@1.0.3
│ │ │   │ │   ├── string_decoder@0.10.31
│ │ │   │ │   └── util-deprecate@1.0.1
│ │ │   │ └── timed-out@2.0.0
│ │ │   └─┬ registry-url@3.0.3
│ │ │     └─┬ rc@1.1.2
│ │ │       ├── deep-extend@0.2.11
│ │ │       ├── ini@1.3.4
│ │ │       ├── minimist@1.2.0
│ │ │       └── strip-json-comments@0.1.3
│ │ ├─┬ semver-diff@2.0.0
│ │ │ └── semver@4.3.6
│ │ └─┬ string-length@1.0.1
│ │   └─┬ strip-ansi@3.0.0
│ │     └── ansi-regex@2.0.0
│ ├── user-home@1.1.1
│ └─┬ which@1.1.2
│   └─┬ is-absolute@0.1.7
│     └── is-relative@0.1.3
├─┬ chai@2.3.0
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
├─┬ express@4.10.8
│ ├─┬ accepts@1.1.4
│ │ ├─┬ mime-types@2.0.14
│ │ │ └── mime-db@1.12.0
│ │ └── negotiator@0.4.9
│ ├── content-disposition@0.5.0
│ ├── cookie@0.1.2
│ ├── cookie-signature@1.0.5
│ ├─┬ debug@2.1.3
│ │ └── ms@0.7.0
│ ├── depd@1.0.1
│ ├── escape-html@1.0.1
│ ├─┬ etag@1.5.1
│ │ └── crc@3.2.1
│ ├── finalhandler@0.3.3
│ ├── fresh@0.2.4
│ ├── media-typer@0.3.0
│ ├── merge-descriptors@0.0.2
│ ├── methods@1.1.1
│ ├─┬ on-finished@2.2.1
│ │ └── ee-first@1.1.0
│ ├── parseurl@1.3.0
│ ├── path-to-regexp@0.1.3
│ ├─┬ proxy-addr@1.0.8
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.0.1
│ ├── qs@2.3.3
│ ├── range-parser@1.0.2
│ ├─┬ send@0.10.1
│ │ ├── destroy@1.0.3
│ │ ├── mime@1.2.11
│ │ ├── ms@0.6.2
│ │ └─┬ on-finished@2.1.1
│ │   └── ee-first@1.1.0
│ ├── serve-static@1.7.2
│ ├─┬ type-is@1.5.7
│ │ └─┬ mime-types@2.0.14
│ │   └── mime-db@1.12.0
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ grunt@0.4.5
│ ├── async@0.1.22
│ ├── coffee-script@1.3.3
│ ├── colors@0.6.2
│ ├── dateformat@1.0.2-1.2.3
│ ├── eventemitter2@0.4.14
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.1.3
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.7.0
│ │ │   └── sigmund@1.0.1
│ │ └── lodash@2.4.2
│ ├── getobject@0.1.0
│ ├─┬ glob@3.1.21
│ │ ├── graceful-fs@1.2.3
│ │ └── inherits@1.0.2
│ ├─┬ grunt-legacy-log@0.1.2
│ │ ├── grunt-legacy-log-utils@0.1.1
│ │ ├── lodash@2.4.2
│ │ └── underscore.string@2.3.3
│ ├── grunt-legacy-util@0.2.0
│ ├── hooker@0.2.3
│ ├── iconv-lite@0.2.11
│ ├─┬ js-yaml@2.0.5
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── underscore@1.7.0
│ │ │ └── underscore.string@2.4.0
│ │ └── esprima@1.0.4
│ ├── lodash@0.9.2
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.7.0
│ │ └── sigmund@1.0.1
│ ├─┬ nopt@1.0.10
│ │ └── abbrev@1.0.7
│ ├── rimraf@2.2.8
│ ├── underscore.string@2.2.1
│ └── which@1.0.9
├── grunt-mocha-istanbul@2.4.0
├─┬ grunt-mocha-test@0.12.7
│ ├── hooker@0.2.3
│ └─┬ mkdirp@0.5.1
│   └── minimist@0.0.8
├── grunt-simple-mocha@0.4.0
├── ip@1.0.1
├─┬ istanbul@0.3.21
│ ├── abbrev@1.0.7
│ ├── async@1.4.2
│ ├─┬ escodegen@1.6.1
│ │ ├── esprima@1.2.5
│ │ ├── estraverse@1.9.3
│ │ ├── esutils@1.1.6
│ │ ├─┬ optionator@0.5.0
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├── levn@0.2.5
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.1
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ source-map@0.1.43
│ │   └── amdefine@1.0.0
│ ├── esprima@2.5.0
│ ├─┬ fileset@0.2.1
│ │ ├─┬ glob@5.0.15
│ │ │ ├─┬ inflight@1.0.4
│ │ │ │ └── wrappy@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ └── path-is-absolute@1.0.0
│ │ └─┬ minimatch@2.0.10
│ │   └─┬ brace-expansion@1.1.1
│ │     ├── balanced-match@0.2.0
│ │     └── concat-map@0.0.1
│ ├─┬ handlebars@4.0.3
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ ├─┬ source-map@0.4.4
│ │ │ └── amdefine@1.0.0
│ │ └─┬ uglify-js@2.4.24
│ │   ├── async@0.2.10
│ │   ├─┬ source-map@0.1.34
│ │   │ └── amdefine@1.0.0
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.5.4
│ │     ├── camelcase@1.2.1
│ │     ├── decamelize@1.0.0
│ │     ├── window-size@0.1.0
│ │     └── wordwrap@0.0.2
│ ├─┬ js-yaml@3.4.2
│ │ ├─┬ argparse@1.0.2
│ │ │ ├── lodash@3.10.1
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.2.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── nopt@3.0.4
│ ├─┬ once@1.3.2
│ │ └── wrappy@1.0.1
│ ├── resolve@1.1.6
│ ├─┬ supports-color@3.1.1
│ │ └── has-flag@1.0.0
│ ├─┬ which@1.1.2
│ │ └─┬ is-absolute@0.1.7
│ │   └── is-relative@0.1.3
│ └── wordwrap@1.0.0
├─┬ jade@1.3.1
│ ├── character-parser@1.2.0
│ ├── commander@2.1.0
│ ├─┬ constantinople@2.0.1
│ │ └─┬ uglify-js@2.4.24
│ │   ├── async@0.2.10
│ │   ├─┬ source-map@0.1.34
│ │   │ └── amdefine@1.0.0
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.5.4
│ │     ├── camelcase@1.2.1
│ │     ├── decamelize@1.0.0
│ │     ├── window-size@0.1.0
│ │     └── wordwrap@0.0.2
│ ├── mkdirp@0.3.5
│ ├─┬ monocle@1.1.51
│ │ └─┬ readdirp@0.2.5
│ │   └─┬ minimatch@3.0.0
│ │     └─┬ brace-expansion@1.1.1
│ │       ├── balanced-match@0.2.0
│ │       └── concat-map@0.0.1
│ ├─┬ transformers@2.1.0
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.1
│ │ └─┬ uglify-js@2.2.5
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.3
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.0
│ └─┬ with@3.0.1
│   └─┬ uglify-js@2.4.24
│     ├── async@0.2.10
│     ├─┬ source-map@0.1.34
│     │ └── amdefine@1.0.0
│     ├── uglify-to-browserify@1.0.2
│     └─┬ yargs@3.5.4
│       ├── camelcase@1.2.1
│       ├── decamelize@1.0.0
│       ├── window-size@0.1.0
│       └── wordwrap@0.0.2
├─┬ mocha@2.3.3
│ ├── commander@2.3.0
│ ├─┬ debug@2.0.0
│ │ └── ms@0.6.2
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.0
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
├── mockery@1.4.0
├─┬ morgan@1.6.1
│ ├── basic-auth@1.0.3
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.0.1
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ └── on-headers@1.0.1
├─┬ nock@2.13.0
│ ├─┬ debug@1.0.4
│ │ └── ms@0.6.2
│ ├── deep-equal@1.0.1
│ ├── lodash@2.4.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── propagate@0.3.1
├─┬ node-persist@0.0.3
│ ├── mkdirp@0.3.5
│ └── q@1.1.2
├─┬ node-schedule@0.1.16
│ ├── cron-parser@0.3.6
│ └── long-timeout@0.0.2
├── node-upnp-ssdp@0.0.3
├── node-uuid@1.4.3
├─┬ sinon@1.17.1
│ ├── formatio@1.1.1
│ ├── lolex@1.3.2
│ ├── samsam@1.1.2
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
├── sinon-chai@2.8.0
├── underscore@1.8.3
├─┬ winston@1.0.2
│ ├── async@1.0.0
│ ├── colors@1.0.3
│ ├── cycle@1.0.3
│ ├── eyes@0.1.8
│ ├── isstream@0.1.2
│ ├── pkginfo@0.3.0
│ └── stack-trace@0.0.9
├─┬ xml2js@0.4.12
│ ├── sax@1.1.3
│ └─┬ xmlbuilder@3.1.0
│   └── lodash@3.10.1
└── zpad@0.5.0

So it looks like everything is installed properly. However, the service is not installed, nothing in

  /etc/init.d

   pi@Bedroom ~/upnp-playlist-service $ sudo service upnp-playlist-service start
   upnp-playlist-service: unrecognised service

Can I start the application in a different way?

**Comment by bazwilliams** [comment]
Yes. The unit scripts are starting the app.js script in server/.

Run:
`node server/app.js`

**Comment by guussie** [comment]
Now I reproduce your error:

pi@Bedroom ~/upnp-playlist-service $ node server/app.js

dgram.js:88
  throw new Error('Bad socket type specified. Valid types are: udp4, udp6');
        ^
Error: Bad socket type specified. Valid types are: udp4, udp6
    at newHandle (dgram.js:88:9)
    at new Socket (dgram.js:113:16)
    at Object.exports.createSocket (dgram.js:130:10)
    at new Ssdp (/home/pi/upnp-playlist-service/node_modules/node-upnp-ssdp/index.js:83:25)
    at Object.<anonymous> (/home/pi/upnp-playlist-service/node_modules/node-upnp-ssdp/index.js:128:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by bazwilliams** [comment]
Great! That means it isn't just my machine. I'll have a look over the weekend to see if I can fix this issue. 

Once I have, I'll properly document raspbi installation.

**Comment by guussie** [comment]
That would be fantastic!

By the way, I have an experimental RPi 2 running Jessie. When I tried to install there I got a whole load of error messages and stopped the effort.

Once you have the RPi solution, I can try the installation on that machine again.

Thanks!

**Comment by guussie** [comment]
Any progress on the Raspberry Pi front?

Thanks!

Guus

**Comment by bazwilliams** [comment]
Not yet I'm afraid, I think it is a distribution problem. Though haven't raised it. You say you have a Raspberry Pi 2? Have you tried the officially released version of Node? I only have a Raspberry Pi 1.

**Comment by bazwilliams** [comment]
I've finally got around to installing node v4 on my Raspberry PI using this guide: http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/

The service should work fine using this version.

**Comment by guussie** [comment]
I got it working! Thanks!

**Comment by bazwilliams** [comment]
Excellent - let me know if you have any issues or suggestions!

**Comment by guussie** [comment]
One more question: how can I install and start at boot as a service? The instructions you have for Debian don't seem to work. Thanks!

**Comment by bazwilliams** [comment]
The init scripts I've written will only work if the app is installed in the /opt/ folder. It is possible you can set all this up. 

But...

I started using node-red about a year ago which at that time suggested 'pm2' as a process and startup manager for node apps. I use this for both node-red and another of my apps domoticz-sound-detection. 

Have a look at the docs here: https://github.com/Unitech/pm2 and a quickstart here: http://pm2.keymetrics.io/docs/usage/quick-start/

**Comment by bazwilliams** [comment]
A quick check on my init script also requires a `nodejs` user and group which the debian packager sets up. 

So, to use my init script: 
Install into `/opt/upnp-playlist-service`
Setup a user and group called `nodejs`

The script also expects the node executable to be called `nodejs`. You can modify line 69 of the init script from `NAME=nodejs` to `NAME=node`.
